id: P003140
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG23845
  title: འབྲུག་པ་བཀའ་བརྒྱུད་ཀྱི་བྱུང་ཚུལ་མདོར་བསྡུས་བདུད་རྩིའི་ཟེག་མ།
  author: ''
  volumes:
    c150040663014de4b11e3160f3d7b7e2:
      image_group_id: I1KG24043
      title: ''
      volume_number: 1
      total_pages: 34
      base_file: v001.txt
